import { registerAs } from '@nestjs/config';
import { DATABASE } from '../constants';

export const databaseConfig = registerAs(DATABASE.NAME, () => ({
  NAME: DATABASE.NAME,
  MONGO_URI: process.env.MONGO_URL || 'mongodb://127.0.0.1:27017/database',
  TESTING_COLLECTION: DATABASE.TESTING_COLLECTION,
  BLOG_COLLECTION: DATABASE.BLOG_COLLECTION,
  COMMENTS_COLLECTION: DATABASE.COMMENTS_COLLECTION,
  POSTS_COLLECTION: DATABASE.POSTS_COLLECTION,
  USERS_COLLECTION: DATABASE.USERS_COLLECTION,
}));
